name: Toffee Auto Update

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:      
  push:
    paths:
      - 'tf.zip'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y p7zip-full
          pip install requests

      - name: Extract Script
        run: |
          mkdir -p tmp_script
          7z x tf.zip -p"${{ secrets.TOFFEE_ZIP_PASSWORD }}" -y -otmp_script

      - name: Run Python Script
        run: python3 tmp_script/tf.py

      - name: Cleanup
        run: rm -rf tmp_script

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Asim Dipto"
          git config --global user.email "asimdipto@github.com"
          git add toffee_NS_Player.m3u toffee_OTT_Navigator.m3u toffee_channel_data.json
          git commit -m "Auto Update Run ID: ${{ github.run_id }}" || exit 0
          git pull origin main --rebase
          git push origin main
